<a href="https://colab.research.google.com/github/gustavoalcantara/geobr_python/blob/main/microrregioes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install geobr

# Nova seção

In [ ]:
import geobr
import pandas as pd
import numpy as np

In [ ]:
micro = geobr.read_micro_region(year=2020)

/usr/local/lib/python3.7/dist-packages/geopandas/array.py:93: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  aout[:] = out

In [ ]:
micro

,code_state,abbrev_state,name_state,code_micro,name_micro,geometry
0,11.0,RO,Rondônia,11001.0,Porto Velho,"MULTIPOLYGON (((-63.09956 -9.48078, -63.10231 ..."
1,11.0,RO,Rondônia,11002.0,Guajará-Mirim,"MULTIPOLYGON (((-64.59455 -12.21570, -64.60819..."
2,11.0,RO,Rondônia,11003.0,Ariquemes,"MULTIPOLYGON (((-63.07681 -9.52497, -63.00059 ..."
3,11.0,RO,Rondônia,11004.0,Ji-Paraná,"MULTIPOLYGON (((-62.66994 -10.28821, -62.61753..."
4,11.0,RO,Rondônia,11005.0,Alvorada D'oeste,"MULTIPOLYGON (((-63.60484 -11.60206, -63.60307..."
...,...,...,...,...,...,...
553,52.0,GO,Goiás,52015.0,Meia Ponte,"MULTIPOLYGON (((-49.82553 -17.58520, -49.82204..."
554,52.0,GO,Goiás,52016.0,Pires Do Rio,"MULTIPOLYGON (((-48.78747 -16.83600, -48.79014..."
555,52.0,GO,Goiás,52017.0,Catalão,"MULTIPOLYGON (((-47.40791 -18.14187, -47.41194..."
556,52.0,GO,Goiás,52018.0,Quirinópolis,"MULTIPOLYGON (((-50.10789 -18.32532, -50.10621..."
557,53.0,DF,Distrito Federal,53001.0,Brasília,"MULTIPOLYGON (((-47.41734 -15.54655, -47.41402..."

In [ ]:
micro['code_state'] = micro['code_state'].astype(np.int64)
micro['code_micro'] = micro['code_micro'].astype(np.int64)

In [ ]:
micro

,code_state,abbrev_state,name_state,code_micro,name_micro,geometry
0,11,RO,Rondônia,11001,Porto Velho,"MULTIPOLYGON (((-63.09956 -9.48078, -63.10231 ..."
1,11,RO,Rondônia,11002,Guajará-Mirim,"MULTIPOLYGON (((-64.59455 -12.21570, -64.60819..."
2,11,RO,Rondônia,11003,Ariquemes,"MULTIPOLYGON (((-63.07681 -9.52497, -63.00059 ..."
3,11,RO,Rondônia,11004,Ji-Paraná,"MULTIPOLYGON (((-62.66994 -10.28821, -62.61753..."
4,11,RO,Rondônia,11005,Alvorada D'oeste,"MULTIPOLYGON (((-63.60484 -11.60206, -63.60307..."
...,...,...,...,...,...,...
553,52,GO,Goiás,52015,Meia Ponte,"MULTIPOLYGON (((-49.82553 -17.58520, -49.82204..."
554,52,GO,Goiás,52016,Pires Do Rio,"MULTIPOLYGON (((-48.78747 -16.83600, -48.79014..."
555,52,GO,Goiás,52017,Catalão,"MULTIPOLYGON (((-47.40791 -18.14187, -47.41194..."
556,52,GO,Goiás,52018,Quirinópolis,"MULTIPOLYGON (((-50.10789 -18.32532, -50.10621..."
557,53,DF,Distrito Federal,53001,Brasília,"MULTIPOLYGON (((-47.41734 -15.54655, -47.41402..."

In [ ]:
micro=micro.rename({'code_state':'id_uf', 'abbrev_state':'sigla_uf', 'code_micro':'id_microrregiao','geometry':'geometria', 'name_micro': 'nome_microrregiao'},axis='columns')

In [ ]:
micro=micro.filter(items=['id_uf', 'sigla_uf', 'id_microrregiao', 'geometria'])

In [ ]:
micro

,id_uf,sigla_uf,id_microrregiao,geometria
0,11,RO,11001,"MULTIPOLYGON (((-63.09956 -9.48078, -63.10231 ..."
1,11,RO,11002,"MULTIPOLYGON (((-64.59455 -12.21570, -64.60819..."
2,11,RO,11003,"MULTIPOLYGON (((-63.07681 -9.52497, -63.00059 ..."
3,11,RO,11004,"MULTIPOLYGON (((-62.66994 -10.28821, -62.61753..."
4,11,RO,11005,"MULTIPOLYGON (((-63.60484 -11.60206, -63.60307..."
...,...,...,...,...
553,52,GO,52015,"MULTIPOLYGON (((-49.82553 -17.58520, -49.82204..."
554,52,GO,52016,"MULTIPOLYGON (((-48.78747 -16.83600, -48.79014..."
555,52,GO,52017,"MULTIPOLYGON (((-47.40791 -18.14187, -47.41194..."
556,52,GO,52018,"MULTIPOLYGON (((-50.10789 -18.32532, -50.10621..."
557,53,DF,53001,"MULTIPOLYGON (((-47.41734 -15.54655, -47.41402..."

In [ ]:
from posixpath import sep

In [ ]:
micro.to_csv('microrregiao.csv', sep=',', index=False, header=True)

In [ ]:
vars(micro)

{'_attrs': {},
 '_crs': None,
 '_flags': <Flags(allows_duplicate_labels=True)>,
 '_geometry_column_name': 'geometry',
 '_is_copy': None,
 '_item_cache': {},
 '_mgr': BlockManager
 Items: Index(['id_uf', 'sigla_uf', 'id_microrregiao', 'geometria'], dtype='object')
 Axis 1: RangeIndex(start=0, stop=558, step=1)
 NumericBlock: slice(0, 4, 2), 2 x 558, dtype: int64
 ObjectBlock: slice(1, 2, 1), 1 x 558, dtype: object
 ExtensionBlock: slice(3, 4, 1), 1 x 558, dtype: geometry,
 '_sindex': None,
 '_sindex_generated': False}